import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
const directory = path.dirname(fileURLToPath(import.meta.url));
const root = path.dirname(directory);
const html = fs.readFileSync(path.join(root, 'software-1c_business1c_zrp_uprav_personal_base.html'), 'utf8');
assert.equal((html.match(/<h1\b/g) || []).length, 1, 'one H1');
assert.equal((html.match(/<details\b/g) || []).length, 10, '9 FAQ entries and technical limits');
const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]);
assert.equal(ids.length, new Set(ids).size, 'unique IDs');
for (const match of html.matchAll(/href="#([^"]+)"/g)) assert(ids.includes(match[1]), `anchor ${match[1]}`);
for (const match of html.matchAll(/(?:src|href)="((?:zup-basic\/|style)[^"]+)"/g)) assert(fs.existsSync(path.join(root, match[1])), `asset ${match[1]}`);
for (const match of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) JSON.parse(match[1]);
const sandbox = { window: {} }; vm.runInNewContext(fs.readFileSync(path.join(directory, 'config.js'), 'utf8'), sandbox);
assert.equal(sandbox.window.ZUP_BASIC.sku, '2900001856744');
assert.equal(sandbox.window.ZUP_BASIC.prices.basic, 11100);
assert(html.includes('11 100 ₽') && html.includes('39 700 ₽') && html.includes('190 900 ₽'));
assert(html.includes('file="header.html"') && html.includes('file="footer.html"'));
assert(html.includes('rel="canonical"') && html.includes('name="description"'));
assert(!html.includes('href="#"'), 'no empty links in new page');
console.log('PASS: H1, metadata, JSON-LD, 10 accordions, unique IDs, anchors, local assets, SSI, SKU, verified prices.');
